name: deploy-to-s3
run-name: ${{ github.actor }} deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: yarn build

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/deploly-to-s3-role
          aws-region: ap-northeast-1

      - name: Deploy
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete
